include:
  - board: nice_nano@2.0.0
    shield: fuji44_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2.0.0
    shield: fuji44_right
  - board: nice_nano@2.0.0
    shield: settings_reset
